SERIAL_DRIVER = vendor
DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes

# MCU = atmega32u4
# BOOTLOADER = caterina
# SPLIT_KEYBOARD = yes